name: 'CDK Code Checks'
description: 'Just an aggregation of the update_environment and code_validation functions for CDK module'
inputs:
  lib-path:
    description: 'The path to the library to be tested.'
    required: true
  pylint-threshold:
    description: "Pylint min threshold to pass"
    required: false
    default: "7"

runs:
  using: 'composite'
  steps:
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pylint ruff isort black
    - name: black run
      continue-on-error: true
      shell: bash
      working-directory: ${{ inputs.lib-path }}
      run: |
        black --check .
    #- name: symilar
    #  shell: bash
    #  working-directory: ${{ inputs.lib-path }}
    #  continue-on-error: true
    #  run: |
    #    find ./src -name "*.py" -print0 | xargs -0 symilar --ignore-docstrings --ignore-imports
    - name: ruff
      shell: bash
      working-directory: ${{ inputs.lib-path }}
      run: |
          ruff check #--config $CYTRO_ROOT/ruff.toml
    - name: isort check
      shell: bash
      working-directory: ${{ inputs.lib-path }}
      run: |
        isort . --check --profile black --filter-files --src $CYTRO_ROOT/lib/cytrolib
