name: 'CDK Code Checks'
description: 'Just an aggregation of the update_environment and code_validation functions for CDK module'
inputs:
  lib-path:
    description: 'The path to the library to be tested.'
    required: true
  pylint-threshold:
    description: "Pylint min threshold to pass"
    required: false
    default: "7"
  build_trigger_dependency:
    description: 'The name of the dependency on which this action runs'
    required: true

runs:
  using: 'composite'
  steps:
    - name: checks
      uses: ./.github/actions/check_differences
      id: check_differences
      with:
        build_trigger_dependency: ${{ inputs.build_trigger_dependency }}
    - name: setup python
      uses: actions/setup-python@v5
      if: steps.check_differences.outputs.check_code_changes == 'true'
      with:
        python-version: '3.12.6'
        # cache: 'poetry'

      run: |
        pip install pylint symilar ruff isort black
    - name: black run
      if: steps.check_differences.outputs.check_code_changes == 'true'
      shell: bash
      working-directory: ${{ inputs.lib-path }}
      run: |
        poetry run black --check .
    - name: symilar
      if: steps.check_differences.outputs.check_code_changes == 'true'
      shell: bash
      working-directory: ${{ inputs.lib-path }}
      continue-on-error: true
      run: |
        find ./src -name "*.py" -print0 | xargs -0 poetry run symilar --ignore-docstrings --ignore-imports
    - name: ruff
      if: steps.check_differences.outputs.check_code_changes == 'true'
      shell: bash
      working-directory: ${{ inputs.lib-path }}
      run: |
          poetry run ruff check #--config $CYTRO_ROOT/ruff.toml
    - name: isort check
      if: steps.check_differences.outputs.check_code_changes == 'true'
      shell: bash
      continue-on-error: true
      working-directory: ${{ inputs.lib-path }}
      run: |
        poetry run isort . --check --profile black --filter-files --src $CYTRO_ROOT/lib/cytrolib
