name: 'Code Check Workflow'

# technically this always runs in Pull rquests, but nowhere else.
on:
  workflow_dispatch:
jobs:
  code_check_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Code pipeline action checks
        uses: ./.github/actions/dummy
